---
title: GTFOBins - Dawn Labs
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md', '/CONTRIBUTING.md']

permalink: pretty

collections:
  gtfobins:
    output: true

defaults:
  - scope:
      path: '_gtfobins'
    values:
      layout: bin
